### ISSUE TITLE
Which function can use like adbkit?

### ISSUE THREAD

**Issue by ZhouYixun** [electricbubble/gadb#1]
哪个方法可以像adbkit一样转发呢？
https://github.com/electricbubble/gadb/blob/master/transport.go
大概看了下是这个文件，但是转发后是大概怎么操作呢？

**Comment by electricbubble** [comment]
你说的转发是指 `gidevice forward`?

如果是的话，可参考[guia2 NewUSBDriver](https://github.com/electricbubble/guia2/blob/caeedcda69a3d750d887ea9b53607ce7477d6ccd/ext.go#L36-L61)

**Comment by ZhouYixun** [comment]
> 你说的转发是指 `gidevice forward`?
> 
> 如果是的话，可参考[guia2 NewUSBDriver](https://github.com/electricbubble/guia2/blob/caeedcda69a3d750d887ea9b53607ce7477d6ccd/ext.go#L36-L61)

不是，是adb远程connect的功能。
 例如a机器启动某个服务，b机器可以通过a机器的ip+端口来adb connect连接

**Comment by electricbubble** [comment]
你说的 `a机器` 是指 `Android 设备`?

`b机器` 是指 `PC`?

---

如果只是 `adb` 的 `connect` 功能，👇
https://github.com/electricbubble/gadb/blob/0080b6dc09c9ebf55524498c7d7e4160ba52e15b/client_test.go#L91-L103

**Comment by ZhouYixun** [comment]
> 你说的 `a机器` 是指 `Android 设备`?
> 
> `b机器` 是指 `PC`?
> 
> 如果只是 `adb` 的 `connect` 功能，👇
> 
> https://github.com/electricbubble/gadb/blob/0080b6dc09c9ebf55524498c7d7e4160ba52e15b/client_test.go#L91-L103
> 
> https://github.com/electricbubble/gadb/blob/0080b6dc09c9ebf55524498c7d7e4160ba52e15b/client.go#L132-L145

机器都是pc，就是可以将本pc的adb的设备转发出去。然后另一个pc可以通过adb connect来连接。这就是adbkit的一个功能

**Comment by ZhouYixun** [comment]
https://github.com/DeviceFarmer/adbkit/tree/master/src/adb/tcpusb 就是这里的

**Comment by ZhouYixun** [comment]
翻了下gadb没实现这个，但是我ts不太熟哈哈哈，不知道你感兴趣吗

**Comment by electricbubble** [comment]
> 就是可以将本pc的adb的设备转发出去。然后另一个pc可以通过adb connect来连接。

实现一个 proxy 就行了，不难，
但这功能不符合本项目的实现目的

**Comment by ZhouYixun** [comment]
> > 就是可以将本pc的adb的设备转发出去。然后另一个pc可以通过adb connect来连接。
> 
> 实现一个 proxy 就行了，不难， 但这功能不符合本项目的实现目的

嗯明白，那我自己试下
